# Generated by Django 4.2.1 on 2023-05-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='change_date',
            field=models.DateField(auto_now=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creat_date',
            field=models.DateField(auto_now=True, verbose_name='дата создания'),
        ),
    ]
