# Generated by Django 4.2.1 on 2023-06-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
