# Generated by Django 4.2.1 on 2023-06-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('create_date',), 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
